"""tag_enum

Revision ID: 702a28378175
Revises: a031dc8879d1
Create Date: 2026-01-18 17:20:37.284929

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '702a28378175'
down_revision = 'a031dc8879d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # VARCHAR -> ENUM(tag_type)
    op.execute(
        "ALTER TABLE tags "
        "ALTER COLUMN name TYPE tag_type "
        "USING name::tag_type"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ENUM(tag_type) -> VARCHAR
    op.execute(
        "ALTER TABLE tags "
        "ALTER COLUMN name TYPE VARCHAR "
        "USING name::text"
    )
    # ### end Alembic commands ###
