"""del_user_in_userauthidentity

Revision ID: 8b5aafb907c3
Revises: 702a28378175
Create Date: 2026-01-18 18:16:41.839799

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8b5aafb907c3'
down_revision = '702a28378175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
